all:
  hosts:
    k8s-master-0:
      ansible_host: 10.0.51.150
      ip: 10.0.51.150
      access_ip: 10.0.51.150
    k8s-worker-0:
      ansible_host: 10.0.51.160
      ip: 10.0.51.160
      access_ip: 10.0.51.160
    k8s-worker-1:
      ansible_host: 10.0.51.161
      ip: 10.0.51.161
      access_ip: 10.0.51.161
    k8s-worker-2:
      ansible_host: 10.0.51.162
      ip: 10.0.51.162
      access_ip: 10.0.51.162
  children:
    kube_control_plane:
      hosts:
        k8s-master-0:
    kube_node:
      hosts:
        k8s-worker-0:
        k8s-worker-1:
        k8s-worker-2:
    etcd:
      hosts:
        k8s-master-0:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
